baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Blog of Joel Thaduri'
themes = "hugo-blog-awesome"
[module]
  [[module.imports]]
    path = "https://github.com/hugo-sid/hugo-blog-awesome/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/hugo-sid/"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/"

[[params.socialIcons]]
name = "Rss"
url = "index.xml"

[params]
  goToTop = true
